<!DOCTYPE html>
<html>
	<head>

		<meta charset="utf-8">
		<?php echo $this->headTitle()->append($this->title) ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink() ?>


	</head>
	<body>

		<?php echo $this->partial('_header.phtml'); ?>
		<div class="container">
			<?php echo $this->layout()->content; ?>
		</div>
		<?php echo $this->partial('_footer.phtml'); ?>

		<?php echo $this->headScript() ?>

	</body>
</html>
